name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Clean workspace
      run: |
        rm -rf ./* || true
        rm -rf ./.* || true
    
    - uses: actions/checkout@v2
      with:
        clean: true
        fetch-depth: 1
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'
        architecture: 'arm64'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip wheel setuptools
        pip install --only-binary :all: numpy==1.24.3
        pip install --only-binary :all: pandas==2.0.3
        pip install -r requirements.txt
    
    - name: Setup Docker Runtime
      run: |
        brew install colima
        colima start
        # Wait for Colima to be ready
        for i in {1..30}; do
          if docker info > /dev/null 2>&1; then
            echo "Docker runtime is ready"
            break
          fi
          echo "Waiting for Docker runtime... ($i/30)"
          sleep 5
        done
    
    - name: Build Docker image
      run: |
        docker build -t acupuncture-api .
        # Add your docker push commands here if needed
    
    # Add deployment steps as needed