name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Clean workspace
      run: |
        rm -rf ./* || true
        rm -rf ./.* || true
    
    - uses: actions/checkout@v2
      with:
        clean: true
        fetch-depth: 1
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'
        architecture: 'arm64'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip wheel setuptools
        pip install --only-binary :all: numpy==1.24.3
        pip install --only-binary :all: pandas==2.0.3
        pip install -r requirements.txt
    
    - name: Setup Docker
      run: |
        # Start Docker Desktop
        open -a Docker
        # Wait for Docker to start
        for i in {1..60}; do
          if docker info > /dev/null 2>&1; then
            echo "Docker is running"
            break
          fi
          echo "Waiting for Docker... ($i/60)"
          sleep 5
        done
    
    - name: Build Docker image
      run: |
        docker build -t acupuncture-api .
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Configure Docker for GCP
      run: |
        gcloud auth configure-docker
    
    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/acupuncture-api .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/acupuncture-api
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy acupuncture-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/acupuncture-api \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated