name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Clean workspace
      run: |
        rm -rf ./* || true
        rm -rf ./.* || true
    
    - uses: actions/checkout@v2
      with:
        clean: true
        fetch-depth: 1
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build and push Docker image
      run: |
        docker build -t acupuncture-api .
        # Add your docker push commands here if needed
    
    # Add deployment steps as needed